// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Recipe struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Ingredients  string
	Instructions sql.NullString
	Notes        sql.NullString
	ImgLink      sql.NullString
	UserID       interface{}
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    string
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Premium        bool
	Email          string
	HashedPassword string
}
